CREATE TABLE payments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id        BIGINT                                  NOT NULL,
    amount           DECIMAL(10, 2)                          NOT NULL,
    payment_date     TIMESTAMP                               NOT NULL,
    due_date         TIMESTAMP                               NOT NULL,
    status           VARCHAR(50)                             NOT NULL,
    description      VARCHAR(500),
    payment_method   VARCHAR(50),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ALTER COLUMN status SET DEFAULT 'PENDING';

ALTER TABLE payments
    ADD CONSTRAINT fk_payment_parent
        FOREIGN KEY (parent_id)
            REFERENCES parents (id)
            ON DELETE CASCADE;

CREATE INDEX idx_payments_parent_id ON payments (parent_id);
CREATE INDEX idx_payments_status ON payments (status);
CREATE INDEX idx_payments_due_date ON payments (due_date);