CREATE TABLE feedbacks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_id BIGINT                                  NOT NULL,
    pupil_id   BIGINT                                  NOT NULL,
    subject_id BIGINT                                  NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    grade      INT                                     NOT NULL,
    CONSTRAINT pk_feedbacks PRIMARY KEY (id)
);

ALTER TABLE feedbacks
    ADD CONSTRAINT fk_feedbacks_on_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id);

ALTER TABLE feedbacks
    ADD CONSTRAINT fk_feedbacks_on_pupil FOREIGN KEY (pupil_id) REFERENCES pupils (id);

ALTER TABLE feedbacks
    ADD CONSTRAINT fk_feedbacks_on_subject FOREIGN KEY (subject_id) REFERENCES subjects (id);