CREATE TABLE teachers
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_teachers PRIMARY KEY (id)
);

ALTER TABLE teachers
    ADD CONSTRAINT fk_teachers_on_email
        FOREIGN KEY (email)
            REFERENCES users (email)
            ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_teachers_email_unique ON teachers (email);