CREATE TABLE teachers
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_teacher PRIMARY KEY (id)
);

ALTER TABLE teachers
    ADD CONSTRAINT uc_teacher_email UNIQUE (email);

ALTER TABLE teachers
    ADD CONSTRAINT FK_TEACHER_ON_EMAIL FOREIGN KEY (email) REFERENCES users (email);