CREATE TABLE parents
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_parents PRIMARY KEY (id)
);

ALTER TABLE parents
    ADD CONSTRAINT fk_parents_on_email
        FOREIGN KEY (email)
            REFERENCES users (email)
            ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_parents_email_unique ON parents (email);