CREATE TABLE parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

ALTER TABLE parents
    ADD CONSTRAINT uc_parents_email UNIQUE (email);

ALTER TABLE parents
    ADD CONSTRAINT fk_parents_user_email
        FOREIGN KEY (email) REFERENCES users (email)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;