CREATE TABLE IF NOT EXISTS classes (
                                       class_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       class_name VARCHAR(255) NOT NULL,
                                       homeroom_teacher_id BIGINT NOT NULL,
                                       CONSTRAINT uc_classes_class_name UNIQUE (class_name)
);

ALTER TABLE classes
    ADD CONSTRAINT fk_classes_homeroom_teacher
        FOREIGN KEY (homeroom_teacher_id)
            REFERENCES teachers (id)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

-- Index to speed lookups by homeroom teacher
CREATE INDEX IF NOT EXISTS idx_classes_homeroom_teacher_id ON classes(homeroom_teacher_id);