CREATE TABLE class
(
    class_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_Name          VARCHAR(255)                            NOT NULL,
    homeroom_teacher_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_class PRIMARY KEY (class_id)
);

ALTER TABLE class
    ADD CONSTRAINT uc_class_class_name UNIQUE (class_Name);