DROP TABLE IF EXISTS class CASCADE;

CREATE TABLE classes
(
    class_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_name           VARCHAR(255)                            NOT NULL,
    homeroom_teacher_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_classes PRIMARY KEY (class_id),
    CONSTRAINT uq_classes_class_name UNIQUE (class_name)
);

ALTER TABLE classes
    ADD CONSTRAINT fk_classes_on_homeroom_teacher
        FOREIGN KEY (homeroom_teacher_id)
            REFERENCES teachers (id)
            ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_classes_homeroom_teacher_id ON classes (homeroom_teacher_id);
