CREATE TABLE pupil
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_id  BIGINT                                  NOT NULL,
    parent_id BIGINT                                  NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pupil PRIMARY KEY (id)
);

ALTER TABLE pupil
    ADD CONSTRAINT uc_pupil_email UNIQUE (email);