CREATE TABLE IF NOT EXISTS pupils (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      class_id BIGINT,
                                      parent_id BIGINT,
                                      email VARCHAR(255) NOT NULL,
                                      CONSTRAINT uc_pupils_email UNIQUE (email)
);

ALTER TABLE pupils
    ADD CONSTRAINT fk_pupils_parent
        FOREIGN KEY (parent_id)
            REFERENCES parents (id)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE pupils
    ADD CONSTRAINT fk_pupils_class
        FOREIGN KEY (class_id)
            REFERENCES classes (class_id)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE pupils
    ADD CONSTRAINT fk_pupils_user_email
        FOREIGN KEY (email)
            REFERENCES users (email)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS idx_pupils_class_id ON pupils(class_id);
CREATE INDEX IF NOT EXISTS idx_pupils_parent_id ON pupils(parent_id);