ALTER TABLE pupil
    ADD CONSTRAINT FK_PUPIL_ON_CLASS FOREIGN KEY (class_id) REFERENCES class (class_id);

ALTER TABLE pupil
    ADD CONSTRAINT FK_PUPIL_ON_EMAIL FOREIGN KEY (email) REFERENCES users (email);

ALTER TABLE pupil ALTER COLUMN class_id DROP NOT NULL;
ALTER TABLE pupil ALTER COLUMN parent_id DROP NOT NULL;