ALTER TABLE pupil
    ADD CONSTRAINT FK_PUPIL_ON_CLASS FOREIGN KEY (class_id) REFERENCES class (class_id);

ALTER TABLE pupil
    ADD CONSTRAINT FK_PUPIL_ON_EMAIL FOREIGN KEY (email) REFERENCES users (email);