CREATE TABLE pupils
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_id  BIGINT,
    parent_id BIGINT,
    email     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pupils PRIMARY KEY (id)
);

ALTER TABLE pupils
    ADD CONSTRAINT fk_pupils_on_email
        FOREIGN KEY (email)
            REFERENCES users (email)
            ON DELETE CASCADE;

ALTER TABLE pupils
    ADD CONSTRAINT fk_pupils_on_class
        FOREIGN KEY (class_id)
            REFERENCES classes (class_id)
            ON DELETE SET NULL;

ALTER TABLE pupils
    ADD CONSTRAINT fk_pupils_on_parent
        FOREIGN KEY (parent_id)
            REFERENCES parents (id)
            ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pupils_email_unique ON pupils (email);

CREATE INDEX IF NOT EXISTS idx_pupils_class_id ON pupils (class_id);
CREATE INDEX IF NOT EXISTS idx_pupils_parent_id ON pupils (parent_id);
