CREATE TABLE announcements
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    admin_id BIGINT                                  NOT NULL,
    class_id BIGINT                                  NOT NULL,
    message  VARCHAR(255)                            NOT NULL,
    date     DATE                                    NOT NULL,
    CONSTRAINT pk_announcements PRIMARY KEY (id)
);

ALTER TABLE announcements
    ADD CONSTRAINT fk_announcements_on_admin FOREIGN KEY (admin_id) REFERENCES admins (id);

ALTER TABLE announcements
    ADD CONSTRAINT fk_announcements_on_class FOREIGN KEY (class_id) REFERENCES classes (class_id);