CREATE TABLE subjects
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

ALTER TABLE subjects
    ADD CONSTRAINT uc_subjects_name UNIQUE (name);