CREATE TABLE schedules
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_id   BIGINT                                  NOT NULL,
    subject_id   BIGINT                                  NOT NULL,
    class_id     BIGINT                                  NOT NULL,
    date         DATE                                    NOT NULL,
    start_hour   TIME                                    NOT NULL,
    end_hour     TIME                                    NOT NULL,
    CONSTRAINT pk_class_schedule PRIMARY KEY (id)
);

ALTER TABLE schedules
    ADD CONSTRAINT fk_schedules_on_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id);

ALTER TABLE schedules
    ADD CONSTRAINT fk_schedules_on_subject FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE schedules
    ADD CONSTRAINT fk_schedules_on_class FOREIGN KEY (class_id) REFERENCES classes (class_id);